export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAIL = "GET_SUB_CATEGORY_FAIL";

export const GET_SINGLE_CATEGORY_REQUEST = "GET_SINGLE_CATEGORY_REQUEST";
export const GET_SINGLE_CATEGORY_SUCCESS = "GET_SINGLE_CATEGORY_SUCCESS";
export const GET_SINGLE_CATEGORY_FAIL = "GET_SINGLE_CATEGORY_FAIL";

export const GET_SINGLE_SUB_CATEGORY_REQUEST =
  "GET_SINGLE_SUB_CATEGORY_REQUEST";
export const GET_SINGLE_SUB_CATEGORY_SUCCESS =
  "GET_SINGLE_SUB_CATEGORY_SUCCESS";
export const GET_SINGLE_SUB_CATEGORY_FAIL = "GET_SINGLE_SUB_CATEGORY_FAIL";
