export const GET_SELLER_REQUEST = "GET_SELLER_REQUEST";
export const GET_SELLER_SUCCESS = "GET_SELLER_SUCCESS";
export const GET_SELLER_FAIL = "GET_SELLER_FAIL";

export const GET_SINGLE_SELLER_REQUEST = "GET_SINGLE_SELLER_REQUEST";
export const GET_SINGLE_SELLER_SUCCESS = "GET_SINGLE_SELLER_SUCCESS";
export const GET_SINGLE_SELLER_FAIL = "GET_SINGLE_SELLER_FAIL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_SINGLE_PRODUCTS_REQUEST = "GET_SINGLE_PRODUCTS_REQUEST";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAIL = "GET_SINGLE_PRODUCTS_FAIL";
